-- Baseline schema for MoneyFlow Service (PostgreSQL).
-- Written to be idempotent so it can run against a fresh database or a database
-- previously created by Hibernate's ddl-auto. New columns introduced together
-- with this change live in later migrations (V2+).

CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    email       VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    first_name  VARCHAR(255) NOT NULL,
    last_name   VARCHAR(255),
    avatar_url  VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS teams (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    invite_code VARCHAR(255) UNIQUE,
    owner_id    BIGINT       NOT NULL REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS accounts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP      NOT NULL,
    updated_at  TIMESTAMP      NOT NULL,
    is_active   BOOLEAN        NOT NULL DEFAULT TRUE,
    user_id     BIGINT         NOT NULL REFERENCES users (id),
    team_id     BIGINT         REFERENCES teams (id),
    name        VARCHAR(255)   NOT NULL,
    type        VARCHAR(255)   NOT NULL,
    balance     NUMERIC(19, 4) NOT NULL,
    currency    VARCHAR(3)     NOT NULL,
    icon        VARCHAR(255),
    color       VARCHAR(255),
    is_default  BOOLEAN        NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    user_id     BIGINT       REFERENCES users (id),
    name        VARCHAR(255) NOT NULL,
    type        VARCHAR(255) NOT NULL,
    icon        VARCHAR(255),
    color       VARCHAR(255),
    is_default  BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS recurring_transactions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP      NOT NULL,
    updated_at          TIMESTAMP      NOT NULL,
    is_active           BOOLEAN        NOT NULL DEFAULT TRUE,
    user_id             BIGINT         NOT NULL REFERENCES users (id),
    account_id          BIGINT         NOT NULL REFERENCES accounts (id),
    category_id         BIGINT         NOT NULL REFERENCES categories (id),
    type                VARCHAR(255)   NOT NULL,
    amount              NUMERIC(19, 4) NOT NULL,
    description         VARCHAR(255)   NOT NULL,
    frequency           VARCHAR(255)   NOT NULL,
    start_date          DATE           NOT NULL,
    end_date            DATE,
    next_execution_date DATE           NOT NULL,
    last_executed_at    TIMESTAMP,
    is_paused           BOOLEAN        NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS transactions (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at               TIMESTAMP      NOT NULL,
    updated_at               TIMESTAMP      NOT NULL,
    is_active                BOOLEAN        NOT NULL DEFAULT TRUE,
    user_id                  BIGINT         NOT NULL REFERENCES users (id),
    account_id               BIGINT         NOT NULL REFERENCES accounts (id),
    category_id              BIGINT         NOT NULL REFERENCES categories (id),
    type                     VARCHAR(255)   NOT NULL,
    amount                   NUMERIC(19, 4) NOT NULL,
    description              VARCHAR(255)   NOT NULL,
    note                     TEXT,
    transaction_date         DATE           NOT NULL,
    reference_number         VARCHAR(255),
    transfer_to_account_id   BIGINT         REFERENCES accounts (id),
    recurring_transaction_id BIGINT         REFERENCES recurring_transactions (id)
);

CREATE INDEX IF NOT EXISTS idx_transaction_user ON transactions (user_id);
CREATE INDEX IF NOT EXISTS idx_transaction_account ON transactions (account_id);
CREATE INDEX IF NOT EXISTS idx_transaction_date ON transactions (transaction_date);
CREATE INDEX IF NOT EXISTS idx_transaction_type ON transactions (type);

CREATE TABLE IF NOT EXISTS budgets (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP      NOT NULL,
    updated_at      TIMESTAMP      NOT NULL,
    is_active       BOOLEAN        NOT NULL DEFAULT TRUE,
    user_id         BIGINT         NOT NULL REFERENCES users (id),
    category_id     BIGINT         NOT NULL REFERENCES categories (id),
    amount          NUMERIC(19, 4) NOT NULL,
    budget_month    INTEGER        NOT NULL,
    budget_year     INTEGER        NOT NULL,
    alert_threshold NUMERIC(5, 2),
    CONSTRAINT uq_budget_user_category_period UNIQUE (user_id, category_id, budget_month, budget_year)
);

CREATE TABLE IF NOT EXISTS team_members (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    team_id    BIGINT       NOT NULL REFERENCES teams (id),
    user_id    BIGINT       NOT NULL REFERENCES users (id),
    role       VARCHAR(255) NOT NULL,
    joined_at  TIMESTAMP    NOT NULL,
    CONSTRAINT uq_team_member UNIQUE (team_id, user_id)
);
