-- Savings goals

CREATE TABLE IF NOT EXISTS savings_goals (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP      NOT NULL,
    updated_at     TIMESTAMP      NOT NULL,
    is_active      BOOLEAN        NOT NULL DEFAULT TRUE,
    version        BIGINT,
    user_id        BIGINT         NOT NULL REFERENCES users (id),
    account_id     BIGINT         REFERENCES accounts (id),
    name           VARCHAR(255)   NOT NULL,
    target_amount  NUMERIC(19, 4) NOT NULL,
    current_amount NUMERIC(19, 4) NOT NULL,
    target_date    DATE,
    icon           VARCHAR(255),
    color          VARCHAR(255),
    status         VARCHAR(255)   NOT NULL
);
