-- Transaction tags + join table

CREATE TABLE IF NOT EXISTS tags (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    version    BIGINT,
    user_id    BIGINT       NOT NULL REFERENCES users (id),
    name       VARCHAR(255) NOT NULL,
    color      VARCHAR(255),
    CONSTRAINT uq_tag_user_name UNIQUE (user_id, name)
);

CREATE TABLE IF NOT EXISTS transaction_tags (
    transaction_id BIGINT NOT NULL REFERENCES transactions (id),
    tag_id         BIGINT NOT NULL REFERENCES tags (id),
    PRIMARY KEY (transaction_id, tag_id)
);
